language: ruby

rvm:
  - 2.7.1

node_js:
  - 14.10.1

services:
  - postgresql

install:
  - bundle install

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - rm -rf bin/webpack*
  - bundle exec rails webpacker:compile

script:
  - bundle exec rspec
 
